[package]
name = "compiler"
description = "The compiler module of the Mosfet Language"
version = "0.1.0"
authors = ["Julio Treviño Páez <julio.tpaez@gmail.com>"]
edition = "2018"
homepage = "https://mosfetlang.org"

[dependencies.parser]
version = "0.1.0"
path = "../parser"